
-- Clean old cid=5 data
DELETE FROM product_variant WHERE pid IN (SELECT pid FROM product WHERE cid = 5);
DELETE FROM product WHERE cid = 5;

-- Insert loungewear products (cid=5, PIDs 375-451)
INSERT INTO product (pid, brand, fabric_type, description, discount, image, name, price, cid, apparel_type, fit_type) VALUES
(375, 'SR FAB', 'Pure Cotton', 'Soft Cotton Lounge Pants - Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-soft-cotton-lounge-pants-grey.png', 'Soft Cotton Lounge Pants - Grey', '699', 5, 'Lounge Pants', 'Relaxed Fit'),
(376, 'SR FAB', 'Pure Cotton', 'Soft Cotton Lounge Pants - Navy Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-soft-cotton-lounge-pants-navy-blue.png', 'Soft Cotton Lounge Pants - Navy Blue', '699', 5, 'Lounge Pants', 'Relaxed Fit'),
(377, 'SR FAB', 'Pure Cotton', 'Soft Cotton Lounge Pants - Black. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-soft-cotton-lounge-pants-black.png', 'Soft Cotton Lounge Pants - Black', '699', 5, 'Lounge Pants', 'Relaxed Fit'),
(378, 'SR FAB', 'Pure Cotton', 'Soft Cotton Lounge Pants - Olive Green. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-soft-cotton-lounge-pants-olive-green.png', 'Soft Cotton Lounge Pants - Olive Green', '699', 5, 'Lounge Pants', 'Relaxed Fit'),
(379, 'SR FAB', 'Pure Cotton', 'Soft Cotton Lounge Pants - Beige. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-soft-cotton-lounge-pants-beige.png', 'Soft Cotton Lounge Pants - Beige', '699', 5, 'Lounge Pants', 'Relaxed Fit'),
(380, 'SR FAB', 'Pure Cotton', 'Soft Cotton Lounge Pants - Charcoal. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-soft-cotton-lounge-pants-charcoal.png', 'Soft Cotton Lounge Pants - Charcoal', '699', 5, 'Lounge Pants', 'Relaxed Fit'),
(381, 'SR FAB', 'Pure Cotton', 'Relax Fit Cotton Lounge Pants - Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-relax-fit-cotton-lounge-pants-grey.png', 'Relax Fit Cotton Lounge Pants - Grey', '699', 5, 'Lounge Pants', 'Relaxed Fit'),
(382, 'SR FAB', 'Pure Cotton', 'Relax Fit Cotton Lounge Pants - Navy Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-relax-fit-cotton-lounge-pants-navy-blue.png', 'Relax Fit Cotton Lounge Pants - Navy Blue', '699', 5, 'Lounge Pants', 'Relaxed Fit'),
(383, 'SR FAB', 'Pure Cotton', 'Relax Fit Cotton Lounge Pants - Black. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-relax-fit-cotton-lounge-pants-black.png', 'Relax Fit Cotton Lounge Pants - Black', '699', 5, 'Lounge Pants', 'Relaxed Fit'),
(384, 'SR FAB', 'Pure Cotton', 'Relax Fit Cotton Lounge Pants - Olive Green. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-relax-fit-cotton-lounge-pants-olive-green.png', 'Relax Fit Cotton Lounge Pants - Olive Green', '699', 5, 'Lounge Pants', 'Relaxed Fit'),
(385, 'SR FAB', 'Pure Cotton', 'Relax Fit Cotton Lounge Pants - Beige. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-relax-fit-cotton-lounge-pants-beige.png', 'Relax Fit Cotton Lounge Pants - Beige', '699', 5, 'Lounge Pants', 'Relaxed Fit'),
(386, 'SR FAB', 'Pure Cotton', 'Relax Fit Cotton Lounge Pants - Charcoal. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-relax-fit-cotton-lounge-pants-charcoal.png', 'Relax Fit Cotton Lounge Pants - Charcoal', '699', 5, 'Lounge Pants', 'Relaxed Fit'),
(387, 'SR FAB', 'Pure Cotton', 'Elastic Waist Cotton Lounge Pants - Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-elastic-waist-cotton-lounge-pants-grey.png', 'Elastic Waist Cotton Lounge Pants - Grey', '699', 5, 'Lounge Pants', 'Regular Fit'),
(388, 'SR FAB', 'Pure Cotton', 'Elastic Waist Cotton Lounge Pants - Navy Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-elastic-waist-cotton-lounge-pants-navy-blue.png', 'Elastic Waist Cotton Lounge Pants - Navy Blue', '699', 5, 'Lounge Pants', 'Regular Fit'),
(389, 'SR FAB', 'Pure Cotton', 'Elastic Waist Cotton Lounge Pants - Black. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-elastic-waist-cotton-lounge-pants-black.png', 'Elastic Waist Cotton Lounge Pants - Black', '699', 5, 'Lounge Pants', 'Regular Fit'),
(390, 'SR FAB', 'Pure Cotton', 'Elastic Waist Cotton Lounge Pants - Olive Green. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-elastic-waist-cotton-lounge-pants-olive-green.png', 'Elastic Waist Cotton Lounge Pants - Olive Green', '699', 5, 'Lounge Pants', 'Regular Fit'),
(391, 'SR FAB', 'Pure Cotton', 'Elastic Waist Cotton Lounge Pants - Beige. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-elastic-waist-cotton-lounge-pants-beige.png', 'Elastic Waist Cotton Lounge Pants - Beige', '699', 5, 'Lounge Pants', 'Regular Fit'),
(392, 'SR FAB', 'Pure Cotton', 'Elastic Waist Cotton Lounge Pants - Charcoal. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-elastic-waist-cotton-lounge-pants-charcoal.png', 'Elastic Waist Cotton Lounge Pants - Charcoal', '699', 5, 'Lounge Pants', 'Regular Fit'),
(393, 'SR FAB', 'Pure Cotton', 'Drawstring Cotton Lounge Pants - Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-drawstring-cotton-lounge-pants-grey.png', 'Drawstring Cotton Lounge Pants - Grey', '699', 5, 'Lounge Pants', 'Regular Fit'),
(394, 'SR FAB', 'Pure Cotton', 'Drawstring Cotton Lounge Pants - Navy Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-drawstring-cotton-lounge-pants-navy-blue.png', 'Drawstring Cotton Lounge Pants - Navy Blue', '699', 5, 'Lounge Pants', 'Regular Fit'),
(395, 'SR FAB', 'Pure Cotton', 'Drawstring Cotton Lounge Pants - Black. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-drawstring-cotton-lounge-pants-black.png', 'Drawstring Cotton Lounge Pants - Black', '699', 5, 'Lounge Pants', 'Regular Fit'),
(396, 'SR FAB', 'Pure Cotton', 'Drawstring Cotton Lounge Pants - Olive Green. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-drawstring-cotton-lounge-pants-olive-green.png', 'Drawstring Cotton Lounge Pants - Olive Green', '699', 5, 'Lounge Pants', 'Regular Fit'),
(397, 'SR FAB', 'Pure Cotton', 'Drawstring Cotton Lounge Pants - Beige. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-drawstring-cotton-lounge-pants-beige.png', 'Drawstring Cotton Lounge Pants - Beige', '699', 5, 'Lounge Pants', 'Regular Fit'),
(398, 'SR FAB', 'Pure Cotton', 'Drawstring Cotton Lounge Pants - Charcoal. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-drawstring-cotton-lounge-pants-charcoal.png', 'Drawstring Cotton Lounge Pants - Charcoal', '699', 5, 'Lounge Pants', 'Regular Fit'),
(399, 'SR FAB', 'Pure Cotton', 'Comfort Cotton Home Wear Pants - Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-comfort-cotton-homewear-pants-grey.png', 'Comfort Cotton Home Wear Pants - Grey', '699', 5, 'Home Wear', 'Relaxed Fit'),
(400, 'SR FAB', 'Pure Cotton', 'Comfort Cotton Home Wear Pants - Navy Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-comfort-cotton-homewear-pants-navy-blue.png', 'Comfort Cotton Home Wear Pants - Navy Blue', '699', 5, 'Home Wear', 'Relaxed Fit'),
(401, 'SR FAB', 'Pure Cotton', 'Comfort Cotton Home Wear Pants - Black. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-comfort-cotton-homewear-pants-black.png', 'Comfort Cotton Home Wear Pants - Black', '699', 5, 'Home Wear', 'Relaxed Fit'),
(402, 'SR FAB', 'Pure Cotton', 'Comfort Cotton Home Wear Pants - Olive Green. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-comfort-cotton-homewear-pants-olive-green.png', 'Comfort Cotton Home Wear Pants - Olive Green', '699', 5, 'Home Wear', 'Relaxed Fit'),
(403, 'SR FAB', 'Pure Cotton', 'Comfort Cotton Home Wear Pants - Beige. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-comfort-cotton-homewear-pants-beige.png', 'Comfort Cotton Home Wear Pants - Beige', '699', 5, 'Home Wear', 'Relaxed Fit'),
(404, 'SR FAB', 'Pure Cotton', 'Comfort Cotton Home Wear Pants - Charcoal. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/lounge-pants-comfort-cotton-homewear-pants-charcoal.png', 'Comfort Cotton Home Wear Pants - Charcoal', '699', 5, 'Home Wear', 'Relaxed Fit'),
(405, 'SR FAB', 'Pure Cotton', 'Classic Cotton Pyjama Pants - Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-classic-cotton-pyjama-pants-grey.png', 'Classic Cotton Pyjama Pants - Grey', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(406, 'SR FAB', 'Pure Cotton', 'Classic Cotton Pyjama Pants - Navy Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-classic-cotton-pyjama-pants-navy-blue.png', 'Classic Cotton Pyjama Pants - Navy Blue', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(407, 'SR FAB', 'Pure Cotton', 'Classic Cotton Pyjama Pants - Black. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-classic-cotton-pyjama-pants-black.png', 'Classic Cotton Pyjama Pants - Black', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(408, 'SR FAB', 'Pure Cotton', 'Classic Cotton Pyjama Pants - Cream. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-classic-cotton-pyjama-pants-cream.png', 'Classic Cotton Pyjama Pants - Cream', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(409, 'SR FAB', 'Pure Cotton', 'Classic Cotton Pyjama Pants - Light Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-classic-cotton-pyjama-pants-light-blue.png', 'Classic Cotton Pyjama Pants - Light Blue', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(410, 'SR FAB', 'Pure Cotton', 'Relaxed Cotton Pyjama Pants - Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-relaxed-cotton-pyjama-pants-grey.png', 'Relaxed Cotton Pyjama Pants - Grey', '649', 5, 'Pyjama Pants', 'Relaxed Fit'),
(411, 'SR FAB', 'Pure Cotton', 'Relaxed Cotton Pyjama Pants - Navy Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-relaxed-cotton-pyjama-pants-navy-blue.png', 'Relaxed Cotton Pyjama Pants - Navy Blue', '649', 5, 'Pyjama Pants', 'Relaxed Fit'),
(412, 'SR FAB', 'Pure Cotton', 'Relaxed Cotton Pyjama Pants - Black. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-relaxed-cotton-pyjama-pants-black.png', 'Relaxed Cotton Pyjama Pants - Black', '649', 5, 'Pyjama Pants', 'Relaxed Fit'),
(413, 'SR FAB', 'Pure Cotton', 'Relaxed Cotton Pyjama Pants - Cream. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-relaxed-cotton-pyjama-pants-cream.png', 'Relaxed Cotton Pyjama Pants - Cream', '649', 5, 'Pyjama Pants', 'Relaxed Fit'),
(414, 'SR FAB', 'Pure Cotton', 'Relaxed Cotton Pyjama Pants - Light Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-relaxed-cotton-pyjama-pants-light-blue.png', 'Relaxed Cotton Pyjama Pants - Light Blue', '649', 5, 'Pyjama Pants', 'Relaxed Fit'),
(415, 'SR FAB', 'Pure Cotton', 'Elastic Waist Pyjama Pants - Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-elastic-waist-pyjama-pants-grey.png', 'Elastic Waist Pyjama Pants - Grey', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(416, 'SR FAB', 'Pure Cotton', 'Elastic Waist Pyjama Pants - Navy Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-elastic-waist-pyjama-pants-navy-blue.png', 'Elastic Waist Pyjama Pants - Navy Blue', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(417, 'SR FAB', 'Pure Cotton', 'Elastic Waist Pyjama Pants - Black. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-elastic-waist-pyjama-pants-black.png', 'Elastic Waist Pyjama Pants - Black', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(418, 'SR FAB', 'Pure Cotton', 'Elastic Waist Pyjama Pants - Cream. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-elastic-waist-pyjama-pants-cream.png', 'Elastic Waist Pyjama Pants - Cream', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(419, 'SR FAB', 'Pure Cotton', 'Elastic Waist Pyjama Pants - Light Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-elastic-waist-pyjama-pants-light-blue.png', 'Elastic Waist Pyjama Pants - Light Blue', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(420, 'SR FAB', 'Pure Cotton', 'Drawstring Cotton Pyjama Pants - Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-drawstring-cotton-pyjama-pants-grey.png', 'Drawstring Cotton Pyjama Pants - Grey', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(421, 'SR FAB', 'Pure Cotton', 'Drawstring Cotton Pyjama Pants - Navy Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-drawstring-cotton-pyjama-pants-navy-blue.png', 'Drawstring Cotton Pyjama Pants - Navy Blue', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(422, 'SR FAB', 'Pure Cotton', 'Drawstring Cotton Pyjama Pants - Black. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-drawstring-cotton-pyjama-pants-black.png', 'Drawstring Cotton Pyjama Pants - Black', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(423, 'SR FAB', 'Pure Cotton', 'Drawstring Cotton Pyjama Pants - Cream. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-drawstring-cotton-pyjama-pants-cream.png', 'Drawstring Cotton Pyjama Pants - Cream', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(424, 'SR FAB', 'Pure Cotton', 'Drawstring Cotton Pyjama Pants - Light Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 12, '/images/products/catalog/pyjama-pants-drawstring-cotton-pyjama-pants-light-blue.png', 'Drawstring Cotton Pyjama Pants - Light Blue', '649', 5, 'Pyjama Pants', 'Regular Fit'),
(425, 'SR FAB', 'Pure Cotton', 'Striped Cotton Pyjama Pants - Blue & White. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 10, '/images/products/catalog/pattern-pyjama-striped-cotton-pyjama-pants-blue-white.png', 'Striped Cotton Pyjama Pants - Blue & White', '749', 5, 'Pyjama Pants', 'Regular Fit'),
(426, 'SR FAB', 'Pure Cotton', 'Striped Cotton Pyjama Pants - Grey & White. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 10, '/images/products/catalog/pattern-pyjama-striped-cotton-pyjama-pants-grey-white.png', 'Striped Cotton Pyjama Pants - Grey & White', '749', 5, 'Pyjama Pants', 'Regular Fit'),
(427, 'SR FAB', 'Pure Cotton', 'Striped Cotton Pyjama Pants - Black & Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 10, '/images/products/catalog/pattern-pyjama-striped-cotton-pyjama-pants-black-grey.png', 'Striped Cotton Pyjama Pants - Black & Grey', '749', 5, 'Pyjama Pants', 'Regular Fit'),
(428, 'SR FAB', 'Pure Cotton', 'Striped Cotton Pyjama Pants - Green & White. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 10, '/images/products/catalog/pattern-pyjama-striped-cotton-pyjama-pants-green-white.png', 'Striped Cotton Pyjama Pants - Green & White', '749', 5, 'Pyjama Pants', 'Regular Fit'),
(429, 'SR FAB', 'Pure Cotton', 'Checked Cotton Pyjama Pants - Blue & White. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 10, '/images/products/catalog/pattern-pyjama-checked-cotton-pyjama-pants-blue-white.png', 'Checked Cotton Pyjama Pants - Blue & White', '749', 5, 'Pyjama Pants', 'Regular Fit'),
(430, 'SR FAB', 'Pure Cotton', 'Checked Cotton Pyjama Pants - Grey & White. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 10, '/images/products/catalog/pattern-pyjama-checked-cotton-pyjama-pants-grey-white.png', 'Checked Cotton Pyjama Pants - Grey & White', '749', 5, 'Pyjama Pants', 'Regular Fit'),
(431, 'SR FAB', 'Pure Cotton', 'Checked Cotton Pyjama Pants - Black & Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 10, '/images/products/catalog/pattern-pyjama-checked-cotton-pyjama-pants-black-grey.png', 'Checked Cotton Pyjama Pants - Black & Grey', '749', 5, 'Pyjama Pants', 'Regular Fit'),
(432, 'SR FAB', 'Pure Cotton', 'Checked Cotton Pyjama Pants - Green & White. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 10, '/images/products/catalog/pattern-pyjama-checked-cotton-pyjama-pants-green-white.png', 'Checked Cotton Pyjama Pants - Green & White', '749', 5, 'Pyjama Pants', 'Regular Fit'),
(433, 'SR FAB', 'Pure Cotton', 'Minimal Pattern Pyjama Pants - Blue & White. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 10, '/images/products/catalog/pattern-pyjama-minimal-pattern-pyjama-pants-blue-white.png', 'Minimal Pattern Pyjama Pants - Blue & White', '749', 5, 'Pyjama Pants', 'Regular Fit'),
(434, 'SR FAB', 'Pure Cotton', 'Minimal Pattern Pyjama Pants - Grey & White. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 10, '/images/products/catalog/pattern-pyjama-minimal-pattern-pyjama-pants-grey-white.png', 'Minimal Pattern Pyjama Pants - Grey & White', '749', 5, 'Pyjama Pants', 'Regular Fit'),
(435, 'SR FAB', 'Pure Cotton', 'Minimal Pattern Pyjama Pants - Black & Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 10, '/images/products/catalog/pattern-pyjama-minimal-pattern-pyjama-pants-black-grey.png', 'Minimal Pattern Pyjama Pants - Black & Grey', '749', 5, 'Pyjama Pants', 'Regular Fit'),
(436, 'SR FAB', 'Pure Cotton', 'Minimal Pattern Pyjama Pants - Green & White. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 10, '/images/products/catalog/pattern-pyjama-minimal-pattern-pyjama-pants-green-white.png', 'Minimal Pattern Pyjama Pants - Green & White', '749', 5, 'Pyjama Pants', 'Regular Fit'),
(437, 'SR FAB', 'Pure Cotton', 'Cotton Night Suit Set - Light Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-night-suit-set-light-grey.png', 'Cotton Night Suit Set - Light Grey', '999', 5, 'Nightwear Set', 'Regular Fit'),
(438, 'SR FAB', 'Pure Cotton', 'Cotton Night Suit Set - Navy Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-night-suit-set-navy-blue.png', 'Cotton Night Suit Set - Navy Blue', '999', 5, 'Nightwear Set', 'Regular Fit'),
(439, 'SR FAB', 'Pure Cotton', 'Cotton Night Suit Set - Sky Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-night-suit-set-sky-blue.png', 'Cotton Night Suit Set - Sky Blue', '999', 5, 'Nightwear Set', 'Regular Fit'),
(440, 'SR FAB', 'Pure Cotton', 'Cotton Night Suit Set - Cream. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-night-suit-set-cream.png', 'Cotton Night Suit Set - Cream', '999', 5, 'Nightwear Set', 'Regular Fit'),
(441, 'SR FAB', 'Pure Cotton', 'Cotton Night Suit Set - Olive Green. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-night-suit-set-olive-green.png', 'Cotton Night Suit Set - Olive Green', '999', 5, 'Nightwear Set', 'Regular Fit'),
(442, 'SR FAB', 'Pure Cotton', 'Cotton Sleep Shirt & Pyjama Set - Light Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-sleep-shirt-pyjama-set-light-grey.png', 'Cotton Sleep Shirt & Pyjama Set - Light Grey', '999', 5, 'Nightwear Set', 'Regular Fit'),
(443, 'SR FAB', 'Pure Cotton', 'Cotton Sleep Shirt & Pyjama Set - Navy Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-sleep-shirt-pyjama-set-navy-blue.png', 'Cotton Sleep Shirt & Pyjama Set - Navy Blue', '999', 5, 'Nightwear Set', 'Regular Fit'),
(444, 'SR FAB', 'Pure Cotton', 'Cotton Sleep Shirt & Pyjama Set - Sky Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-sleep-shirt-pyjama-set-sky-blue.png', 'Cotton Sleep Shirt & Pyjama Set - Sky Blue', '999', 5, 'Nightwear Set', 'Regular Fit'),
(445, 'SR FAB', 'Pure Cotton', 'Cotton Sleep Shirt & Pyjama Set - Cream. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-sleep-shirt-pyjama-set-cream.png', 'Cotton Sleep Shirt & Pyjama Set - Cream', '999', 5, 'Nightwear Set', 'Regular Fit'),
(446, 'SR FAB', 'Pure Cotton', 'Cotton Sleep Shirt & Pyjama Set - Olive Green. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-sleep-shirt-pyjama-set-olive-green.png', 'Cotton Sleep Shirt & Pyjama Set - Olive Green', '999', 5, 'Nightwear Set', 'Regular Fit'),
(447, 'SR FAB', 'Pure Cotton', 'Cotton Sleep T-Shirt & Shorts Set - Light Grey. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-sleep-tshirt-shorts-set-light-grey.png', 'Cotton Sleep T-Shirt & Shorts Set - Light Grey', '999', 5, 'Nightwear Set', 'Relaxed Fit'),
(448, 'SR FAB', 'Pure Cotton', 'Cotton Sleep T-Shirt & Shorts Set - Navy Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-sleep-tshirt-shorts-set-navy-blue.png', 'Cotton Sleep T-Shirt & Shorts Set - Navy Blue', '999', 5, 'Nightwear Set', 'Relaxed Fit'),
(449, 'SR FAB', 'Pure Cotton', 'Cotton Sleep T-Shirt & Shorts Set - Sky Blue. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-sleep-tshirt-shorts-set-sky-blue.png', 'Cotton Sleep T-Shirt & Shorts Set - Sky Blue', '999', 5, 'Nightwear Set', 'Relaxed Fit'),
(450, 'SR FAB', 'Pure Cotton', 'Cotton Sleep T-Shirt & Shorts Set - Cream. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-sleep-tshirt-shorts-set-cream.png', 'Cotton Sleep T-Shirt & Shorts Set - Cream', '999', 5, 'Nightwear Set', 'Relaxed Fit'),
(451, 'SR FAB', 'Pure Cotton', 'Cotton Sleep T-Shirt & Shorts Set - Olive Green. 100% Pure Cotton. Premium comfort for rest, relaxation and sleep.', 15, '/images/products/catalog/nightwear-cotton-sleep-tshirt-shorts-set-olive-green.png', 'Cotton Sleep T-Shirt & Shorts Set - Olive Green', '999', 5, 'Nightwear Set', 'Relaxed Fit');

-- Insert variants
INSERT INTO product_variant (pid, color, size, sku, stock) VALUES
(375, 'Grey', 'S', 'LW-375-S', 21),
(375, 'Grey', 'M', 'LW-375-M', 42),
(375, 'Grey', 'L', 'LW-375-L', 36),
(375, 'Grey', 'XL', 'LW-375-XL', 22),
(375, 'Grey', 'XXL', 'LW-375-XXL', 40),
(376, 'Navy Blue', 'S', 'LW-376-S', 43),
(376, 'Navy Blue', 'M', 'LW-376-M', 25),
(376, 'Navy Blue', 'L', 'LW-376-L', 39),
(376, 'Navy Blue', 'XL', 'LW-376-XL', 47),
(376, 'Navy Blue', 'XXL', 'LW-376-XXL', 32),
(377, 'Black', 'S', 'LW-377-S', 46),
(377, 'Black', 'M', 'LW-377-M', 40),
(377, 'Black', 'L', 'LW-377-L', 25),
(377, 'Black', 'XL', 'LW-377-XL', 24),
(377, 'Black', 'XXL', 'LW-377-XXL', 43),
(378, 'Olive Green', 'S', 'LW-378-S', 34),
(378, 'Olive Green', 'M', 'LW-378-M', 49),
(378, 'Olive Green', 'L', 'LW-378-L', 32),
(378, 'Olive Green', 'XL', 'LW-378-XL', 35),
(378, 'Olive Green', 'XXL', 'LW-378-XXL', 35),
(379, 'Beige', 'S', 'LW-379-S', 48),
(379, 'Beige', 'M', 'LW-379-M', 24),
(379, 'Beige', 'L', 'LW-379-L', 35),
(379, 'Beige', 'XL', 'LW-379-XL', 33),
(379, 'Beige', 'XXL', 'LW-379-XXL', 28),
(380, 'Charcoal', 'S', 'LW-380-S', 42),
(380, 'Charcoal', 'M', 'LW-380-M', 25),
(380, 'Charcoal', 'L', 'LW-380-L', 43),
(380, 'Charcoal', 'XL', 'LW-380-XL', 35),
(380, 'Charcoal', 'XXL', 'LW-380-XXL', 47),
(381, 'Grey', 'S', 'LW-381-S', 24),
(381, 'Grey', 'M', 'LW-381-M', 35),
(381, 'Grey', 'L', 'LW-381-L', 32),
(381, 'Grey', 'XL', 'LW-381-XL', 41),
(381, 'Grey', 'XXL', 'LW-381-XXL', 46),
(382, 'Navy Blue', 'S', 'LW-382-S', 34),
(382, 'Navy Blue', 'M', 'LW-382-M', 25),
(382, 'Navy Blue', 'L', 'LW-382-L', 25),
(382, 'Navy Blue', 'XL', 'LW-382-XL', 45),
(382, 'Navy Blue', 'XXL', 'LW-382-XXL', 39),
(383, 'Black', 'S', 'LW-383-S', 34),
(383, 'Black', 'M', 'LW-383-M', 35),
(383, 'Black', 'L', 'LW-383-L', 25),
(383, 'Black', 'XL', 'LW-383-XL', 21),
(383, 'Black', 'XXL', 'LW-383-XXL', 38),
(384, 'Olive Green', 'S', 'LW-384-S', 49),
(384, 'Olive Green', 'M', 'LW-384-M', 21),
(384, 'Olive Green', 'L', 'LW-384-L', 25),
(384, 'Olive Green', 'XL', 'LW-384-XL', 34),
(384, 'Olive Green', 'XXL', 'LW-384-XXL', 35),
(385, 'Beige', 'S', 'LW-385-S', 20),
(385, 'Beige', 'M', 'LW-385-M', 45),
(385, 'Beige', 'L', 'LW-385-L', 29),
(385, 'Beige', 'XL', 'LW-385-XL', 29),
(385, 'Beige', 'XXL', 'LW-385-XXL', 20),
(386, 'Charcoal', 'S', 'LW-386-S', 27),
(386, 'Charcoal', 'M', 'LW-386-M', 21),
(386, 'Charcoal', 'L', 'LW-386-L', 38),
(386, 'Charcoal', 'XL', 'LW-386-XL', 49),
(386, 'Charcoal', 'XXL', 'LW-386-XXL', 28),
(387, 'Grey', 'S', 'LW-387-S', 21),
(387, 'Grey', 'M', 'LW-387-M', 38),
(387, 'Grey', 'L', 'LW-387-L', 35),
(387, 'Grey', 'XL', 'LW-387-XL', 27),
(387, 'Grey', 'XXL', 'LW-387-XXL', 49),
(388, 'Navy Blue', 'S', 'LW-388-S', 43),
(388, 'Navy Blue', 'M', 'LW-388-M', 27),
(388, 'Navy Blue', 'L', 'LW-388-L', 21),
(388, 'Navy Blue', 'XL', 'LW-388-XL', 21),
(388, 'Navy Blue', 'XXL', 'LW-388-XXL', 35),
(389, 'Black', 'S', 'LW-389-S', 37),
(389, 'Black', 'M', 'LW-389-M', 21),
(389, 'Black', 'L', 'LW-389-L', 38),
(389, 'Black', 'XL', 'LW-389-XL', 20),
(389, 'Black', 'XXL', 'LW-389-XXL', 49),
(390, 'Olive Green', 'S', 'LW-390-S', 44),
(390, 'Olive Green', 'M', 'LW-390-M', 34),
(390, 'Olive Green', 'L', 'LW-390-L', 34),
(390, 'Olive Green', 'XL', 'LW-390-XL', 22),
(390, 'Olive Green', 'XXL', 'LW-390-XXL', 25),
(391, 'Beige', 'S', 'LW-391-S', 21),
(391, 'Beige', 'M', 'LW-391-M', 32),
(391, 'Beige', 'L', 'LW-391-L', 40),
(391, 'Beige', 'XL', 'LW-391-XL', 43),
(391, 'Beige', 'XXL', 'LW-391-XXL', 45),
(392, 'Charcoal', 'S', 'LW-392-S', 32),
(392, 'Charcoal', 'M', 'LW-392-M', 39),
(392, 'Charcoal', 'L', 'LW-392-L', 39),
(392, 'Charcoal', 'XL', 'LW-392-XL', 38),
(392, 'Charcoal', 'XXL', 'LW-392-XXL', 23),
(393, 'Grey', 'S', 'LW-393-S', 31),
(393, 'Grey', 'M', 'LW-393-M', 21),
(393, 'Grey', 'L', 'LW-393-L', 32),
(393, 'Grey', 'XL', 'LW-393-XL', 36),
(393, 'Grey', 'XXL', 'LW-393-XXL', 29),
(394, 'Navy Blue', 'S', 'LW-394-S', 25),
(394, 'Navy Blue', 'M', 'LW-394-M', 32),
(394, 'Navy Blue', 'L', 'LW-394-L', 47),
(394, 'Navy Blue', 'XL', 'LW-394-XL', 39),
(394, 'Navy Blue', 'XXL', 'LW-394-XXL', 47),
(395, 'Black', 'S', 'LW-395-S', 34),
(395, 'Black', 'M', 'LW-395-M', 45),
(395, 'Black', 'L', 'LW-395-L', 34),
(395, 'Black', 'XL', 'LW-395-XL', 36),
(395, 'Black', 'XXL', 'LW-395-XXL', 37),
(396, 'Olive Green', 'S', 'LW-396-S', 26),
(396, 'Olive Green', 'M', 'LW-396-M', 38),
(396, 'Olive Green', 'L', 'LW-396-L', 22),
(396, 'Olive Green', 'XL', 'LW-396-XL', 40),
(396, 'Olive Green', 'XXL', 'LW-396-XXL', 27),
(397, 'Beige', 'S', 'LW-397-S', 44),
(397, 'Beige', 'M', 'LW-397-M', 38),
(397, 'Beige', 'L', 'LW-397-L', 46),
(397, 'Beige', 'XL', 'LW-397-XL', 36),
(397, 'Beige', 'XXL', 'LW-397-XXL', 38),
(398, 'Charcoal', 'S', 'LW-398-S', 43),
(398, 'Charcoal', 'M', 'LW-398-M', 34),
(398, 'Charcoal', 'L', 'LW-398-L', 49),
(398, 'Charcoal', 'XL', 'LW-398-XL', 49),
(398, 'Charcoal', 'XXL', 'LW-398-XXL', 33),
(399, 'Grey', 'S', 'LW-399-S', 37),
(399, 'Grey', 'M', 'LW-399-M', 20),
(399, 'Grey', 'L', 'LW-399-L', 39),
(399, 'Grey', 'XL', 'LW-399-XL', 34),
(399, 'Grey', 'XXL', 'LW-399-XXL', 43),
(400, 'Navy Blue', 'S', 'LW-400-S', 31),
(400, 'Navy Blue', 'M', 'LW-400-M', 46),
(400, 'Navy Blue', 'L', 'LW-400-L', 42),
(400, 'Navy Blue', 'XL', 'LW-400-XL', 32),
(400, 'Navy Blue', 'XXL', 'LW-400-XXL', 43),
(401, 'Black', 'S', 'LW-401-S', 29),
(401, 'Black', 'M', 'LW-401-M', 39),
(401, 'Black', 'L', 'LW-401-L', 47),
(401, 'Black', 'XL', 'LW-401-XL', 31),
(401, 'Black', 'XXL', 'LW-401-XXL', 45),
(402, 'Olive Green', 'S', 'LW-402-S', 21),
(402, 'Olive Green', 'M', 'LW-402-M', 41),
(402, 'Olive Green', 'L', 'LW-402-L', 21),
(402, 'Olive Green', 'XL', 'LW-402-XL', 41),
(402, 'Olive Green', 'XXL', 'LW-402-XXL', 42),
(403, 'Beige', 'S', 'LW-403-S', 49),
(403, 'Beige', 'M', 'LW-403-M', 24),
(403, 'Beige', 'L', 'LW-403-L', 40),
(403, 'Beige', 'XL', 'LW-403-XL', 34),
(403, 'Beige', 'XXL', 'LW-403-XXL', 29),
(404, 'Charcoal', 'S', 'LW-404-S', 44),
(404, 'Charcoal', 'M', 'LW-404-M', 49),
(404, 'Charcoal', 'L', 'LW-404-L', 46),
(404, 'Charcoal', 'XL', 'LW-404-XL', 21),
(404, 'Charcoal', 'XXL', 'LW-404-XXL', 25),
(405, 'Grey', 'S', 'LW-405-S', 29),
(405, 'Grey', 'M', 'LW-405-M', 28),
(405, 'Grey', 'L', 'LW-405-L', 31),
(405, 'Grey', 'XL', 'LW-405-XL', 41),
(405, 'Grey', 'XXL', 'LW-405-XXL', 43),
(406, 'Navy Blue', 'S', 'LW-406-S', 22),
(406, 'Navy Blue', 'M', 'LW-406-M', 44),
(406, 'Navy Blue', 'L', 'LW-406-L', 39),
(406, 'Navy Blue', 'XL', 'LW-406-XL', 34),
(406, 'Navy Blue', 'XXL', 'LW-406-XXL', 33),
(407, 'Black', 'S', 'LW-407-S', 49),
(407, 'Black', 'M', 'LW-407-M', 37),
(407, 'Black', 'L', 'LW-407-L', 48),
(407, 'Black', 'XL', 'LW-407-XL', 33),
(407, 'Black', 'XXL', 'LW-407-XXL', 25),
(408, 'Cream', 'S', 'LW-408-S', 30),
(408, 'Cream', 'M', 'LW-408-M', 48),
(408, 'Cream', 'L', 'LW-408-L', 20),
(408, 'Cream', 'XL', 'LW-408-XL', 29),
(408, 'Cream', 'XXL', 'LW-408-XXL', 30),
(409, 'Light Blue', 'S', 'LW-409-S', 31),
(409, 'Light Blue', 'M', 'LW-409-M', 24),
(409, 'Light Blue', 'L', 'LW-409-L', 21),
(409, 'Light Blue', 'XL', 'LW-409-XL', 47),
(409, 'Light Blue', 'XXL', 'LW-409-XXL', 39),
(410, 'Grey', 'S', 'LW-410-S', 23),
(410, 'Grey', 'M', 'LW-410-M', 46),
(410, 'Grey', 'L', 'LW-410-L', 44),
(410, 'Grey', 'XL', 'LW-410-XL', 36),
(410, 'Grey', 'XXL', 'LW-410-XXL', 24),
(411, 'Navy Blue', 'S', 'LW-411-S', 39),
(411, 'Navy Blue', 'M', 'LW-411-M', 21),
(411, 'Navy Blue', 'L', 'LW-411-L', 39),
(411, 'Navy Blue', 'XL', 'LW-411-XL', 32),
(411, 'Navy Blue', 'XXL', 'LW-411-XXL', 26),
(412, 'Black', 'S', 'LW-412-S', 34),
(412, 'Black', 'M', 'LW-412-M', 45),
(412, 'Black', 'L', 'LW-412-L', 33),
(412, 'Black', 'XL', 'LW-412-XL', 20),
(412, 'Black', 'XXL', 'LW-412-XXL', 42),
(413, 'Cream', 'S', 'LW-413-S', 39),
(413, 'Cream', 'M', 'LW-413-M', 44),
(413, 'Cream', 'L', 'LW-413-L', 31),
(413, 'Cream', 'XL', 'LW-413-XL', 28),
(413, 'Cream', 'XXL', 'LW-413-XXL', 40),
(414, 'Light Blue', 'S', 'LW-414-S', 38),
(414, 'Light Blue', 'M', 'LW-414-M', 25),
(414, 'Light Blue', 'L', 'LW-414-L', 27),
(414, 'Light Blue', 'XL', 'LW-414-XL', 34),
(414, 'Light Blue', 'XXL', 'LW-414-XXL', 35),
(415, 'Grey', 'S', 'LW-415-S', 31),
(415, 'Grey', 'M', 'LW-415-M', 39),
(415, 'Grey', 'L', 'LW-415-L', 26),
(415, 'Grey', 'XL', 'LW-415-XL', 20),
(415, 'Grey', 'XXL', 'LW-415-XXL', 30),
(416, 'Navy Blue', 'S', 'LW-416-S', 43),
(416, 'Navy Blue', 'M', 'LW-416-M', 43),
(416, 'Navy Blue', 'L', 'LW-416-L', 39),
(416, 'Navy Blue', 'XL', 'LW-416-XL', 22),
(416, 'Navy Blue', 'XXL', 'LW-416-XXL', 29),
(417, 'Black', 'S', 'LW-417-S', 46),
(417, 'Black', 'M', 'LW-417-M', 22),
(417, 'Black', 'L', 'LW-417-L', 27),
(417, 'Black', 'XL', 'LW-417-XL', 24),
(417, 'Black', 'XXL', 'LW-417-XXL', 45),
(418, 'Cream', 'S', 'LW-418-S', 38),
(418, 'Cream', 'M', 'LW-418-M', 38),
(418, 'Cream', 'L', 'LW-418-L', 43),
(418, 'Cream', 'XL', 'LW-418-XL', 30),
(418, 'Cream', 'XXL', 'LW-418-XXL', 44),
(419, 'Light Blue', 'S', 'LW-419-S', 35),
(419, 'Light Blue', 'M', 'LW-419-M', 34),
(419, 'Light Blue', 'L', 'LW-419-L', 30),
(419, 'Light Blue', 'XL', 'LW-419-XL', 36),
(419, 'Light Blue', 'XXL', 'LW-419-XXL', 31),
(420, 'Grey', 'S', 'LW-420-S', 21),
(420, 'Grey', 'M', 'LW-420-M', 33),
(420, 'Grey', 'L', 'LW-420-L', 45),
(420, 'Grey', 'XL', 'LW-420-XL', 28),
(420, 'Grey', 'XXL', 'LW-420-XXL', 23),
(421, 'Navy Blue', 'S', 'LW-421-S', 40),
(421, 'Navy Blue', 'M', 'LW-421-M', 37),
(421, 'Navy Blue', 'L', 'LW-421-L', 39),
(421, 'Navy Blue', 'XL', 'LW-421-XL', 25),
(421, 'Navy Blue', 'XXL', 'LW-421-XXL', 47),
(422, 'Black', 'S', 'LW-422-S', 28),
(422, 'Black', 'M', 'LW-422-M', 34),
(422, 'Black', 'L', 'LW-422-L', 33),
(422, 'Black', 'XL', 'LW-422-XL', 38),
(422, 'Black', 'XXL', 'LW-422-XXL', 38),
(423, 'Cream', 'S', 'LW-423-S', 26),
(423, 'Cream', 'M', 'LW-423-M', 24),
(423, 'Cream', 'L', 'LW-423-L', 48),
(423, 'Cream', 'XL', 'LW-423-XL', 29),
(423, 'Cream', 'XXL', 'LW-423-XXL', 22),
(424, 'Light Blue', 'S', 'LW-424-S', 42),
(424, 'Light Blue', 'M', 'LW-424-M', 27),
(424, 'Light Blue', 'L', 'LW-424-L', 45),
(424, 'Light Blue', 'XL', 'LW-424-XL', 33),
(424, 'Light Blue', 'XXL', 'LW-424-XXL', 33),
(425, 'Blue & White', 'S', 'LW-425-S', 44),
(425, 'Blue & White', 'M', 'LW-425-M', 38),
(425, 'Blue & White', 'L', 'LW-425-L', 22),
(425, 'Blue & White', 'XL', 'LW-425-XL', 45),
(425, 'Blue & White', 'XXL', 'LW-425-XXL', 32),
(426, 'Grey & White', 'S', 'LW-426-S', 40),
(426, 'Grey & White', 'M', 'LW-426-M', 20),
(426, 'Grey & White', 'L', 'LW-426-L', 34),
(426, 'Grey & White', 'XL', 'LW-426-XL', 21),
(426, 'Grey & White', 'XXL', 'LW-426-XXL', 46),
(427, 'Black & Grey', 'S', 'LW-427-S', 36),
(427, 'Black & Grey', 'M', 'LW-427-M', 31),
(427, 'Black & Grey', 'L', 'LW-427-L', 32),
(427, 'Black & Grey', 'XL', 'LW-427-XL', 42),
(427, 'Black & Grey', 'XXL', 'LW-427-XXL', 32),
(428, 'Green & White', 'S', 'LW-428-S', 32),
(428, 'Green & White', 'M', 'LW-428-M', 39),
(428, 'Green & White', 'L', 'LW-428-L', 32),
(428, 'Green & White', 'XL', 'LW-428-XL', 28),
(428, 'Green & White', 'XXL', 'LW-428-XXL', 44),
(429, 'Blue & White', 'S', 'LW-429-S', 37),
(429, 'Blue & White', 'M', 'LW-429-M', 29),
(429, 'Blue & White', 'L', 'LW-429-L', 23),
(429, 'Blue & White', 'XL', 'LW-429-XL', 35),
(429, 'Blue & White', 'XXL', 'LW-429-XXL', 20),
(430, 'Grey & White', 'S', 'LW-430-S', 35),
(430, 'Grey & White', 'M', 'LW-430-M', 27),
(430, 'Grey & White', 'L', 'LW-430-L', 25),
(430, 'Grey & White', 'XL', 'LW-430-XL', 22),
(430, 'Grey & White', 'XXL', 'LW-430-XXL', 32),
(431, 'Black & Grey', 'S', 'LW-431-S', 31),
(431, 'Black & Grey', 'M', 'LW-431-M', 32),
(431, 'Black & Grey', 'L', 'LW-431-L', 44),
(431, 'Black & Grey', 'XL', 'LW-431-XL', 26),
(431, 'Black & Grey', 'XXL', 'LW-431-XXL', 38),
(432, 'Green & White', 'S', 'LW-432-S', 48),
(432, 'Green & White', 'M', 'LW-432-M', 36),
(432, 'Green & White', 'L', 'LW-432-L', 38),
(432, 'Green & White', 'XL', 'LW-432-XL', 25),
(432, 'Green & White', 'XXL', 'LW-432-XXL', 25),
(433, 'Blue & White', 'S', 'LW-433-S', 35),
(433, 'Blue & White', 'M', 'LW-433-M', 22),
(433, 'Blue & White', 'L', 'LW-433-L', 20),
(433, 'Blue & White', 'XL', 'LW-433-XL', 20),
(433, 'Blue & White', 'XXL', 'LW-433-XXL', 27),
(434, 'Grey & White', 'S', 'LW-434-S', 39),
(434, 'Grey & White', 'M', 'LW-434-M', 36),
(434, 'Grey & White', 'L', 'LW-434-L', 28),
(434, 'Grey & White', 'XL', 'LW-434-XL', 41),
(434, 'Grey & White', 'XXL', 'LW-434-XXL', 45),
(435, 'Black & Grey', 'S', 'LW-435-S', 25),
(435, 'Black & Grey', 'M', 'LW-435-M', 36),
(435, 'Black & Grey', 'L', 'LW-435-L', 35),
(435, 'Black & Grey', 'XL', 'LW-435-XL', 34),
(435, 'Black & Grey', 'XXL', 'LW-435-XXL', 42),
(436, 'Green & White', 'S', 'LW-436-S', 23),
(436, 'Green & White', 'M', 'LW-436-M', 44),
(436, 'Green & White', 'L', 'LW-436-L', 36),
(436, 'Green & White', 'XL', 'LW-436-XL', 29),
(436, 'Green & White', 'XXL', 'LW-436-XXL', 26),
(437, 'Light Grey', 'S', 'LW-437-S', 25),
(437, 'Light Grey', 'M', 'LW-437-M', 27),
(437, 'Light Grey', 'L', 'LW-437-L', 44),
(437, 'Light Grey', 'XL', 'LW-437-XL', 40),
(437, 'Light Grey', 'XXL', 'LW-437-XXL', 31),
(438, 'Navy Blue', 'S', 'LW-438-S', 20),
(438, 'Navy Blue', 'M', 'LW-438-M', 22),
(438, 'Navy Blue', 'L', 'LW-438-L', 21),
(438, 'Navy Blue', 'XL', 'LW-438-XL', 39),
(438, 'Navy Blue', 'XXL', 'LW-438-XXL', 36),
(439, 'Sky Blue', 'S', 'LW-439-S', 29),
(439, 'Sky Blue', 'M', 'LW-439-M', 21),
(439, 'Sky Blue', 'L', 'LW-439-L', 36),
(439, 'Sky Blue', 'XL', 'LW-439-XL', 31),
(439, 'Sky Blue', 'XXL', 'LW-439-XXL', 30),
(440, 'Cream', 'S', 'LW-440-S', 47),
(440, 'Cream', 'M', 'LW-440-M', 45),
(440, 'Cream', 'L', 'LW-440-L', 33),
(440, 'Cream', 'XL', 'LW-440-XL', 28),
(440, 'Cream', 'XXL', 'LW-440-XXL', 46),
(441, 'Olive Green', 'S', 'LW-441-S', 20),
(441, 'Olive Green', 'M', 'LW-441-M', 42),
(441, 'Olive Green', 'L', 'LW-441-L', 46),
(441, 'Olive Green', 'XL', 'LW-441-XL', 49),
(441, 'Olive Green', 'XXL', 'LW-441-XXL', 41),
(442, 'Light Grey', 'S', 'LW-442-S', 39),
(442, 'Light Grey', 'M', 'LW-442-M', 25),
(442, 'Light Grey', 'L', 'LW-442-L', 20),
(442, 'Light Grey', 'XL', 'LW-442-XL', 49),
(442, 'Light Grey', 'XXL', 'LW-442-XXL', 48),
(443, 'Navy Blue', 'S', 'LW-443-S', 46),
(443, 'Navy Blue', 'M', 'LW-443-M', 42),
(443, 'Navy Blue', 'L', 'LW-443-L', 25),
(443, 'Navy Blue', 'XL', 'LW-443-XL', 34),
(443, 'Navy Blue', 'XXL', 'LW-443-XXL', 40),
(444, 'Sky Blue', 'S', 'LW-444-S', 47),
(444, 'Sky Blue', 'M', 'LW-444-M', 34),
(444, 'Sky Blue', 'L', 'LW-444-L', 31),
(444, 'Sky Blue', 'XL', 'LW-444-XL', 36),
(444, 'Sky Blue', 'XXL', 'LW-444-XXL', 47),
(445, 'Cream', 'S', 'LW-445-S', 23),
(445, 'Cream', 'M', 'LW-445-M', 39),
(445, 'Cream', 'L', 'LW-445-L', 20),
(445, 'Cream', 'XL', 'LW-445-XL', 35),
(445, 'Cream', 'XXL', 'LW-445-XXL', 41),
(446, 'Olive Green', 'S', 'LW-446-S', 23),
(446, 'Olive Green', 'M', 'LW-446-M', 36),
(446, 'Olive Green', 'L', 'LW-446-L', 20),
(446, 'Olive Green', 'XL', 'LW-446-XL', 28),
(446, 'Olive Green', 'XXL', 'LW-446-XXL', 46),
(447, 'Light Grey', 'S', 'LW-447-S', 43),
(447, 'Light Grey', 'M', 'LW-447-M', 27),
(447, 'Light Grey', 'L', 'LW-447-L', 40),
(447, 'Light Grey', 'XL', 'LW-447-XL', 48),
(447, 'Light Grey', 'XXL', 'LW-447-XXL', 26),
(448, 'Navy Blue', 'S', 'LW-448-S', 35),
(448, 'Navy Blue', 'M', 'LW-448-M', 41),
(448, 'Navy Blue', 'L', 'LW-448-L', 27),
(448, 'Navy Blue', 'XL', 'LW-448-XL', 47),
(448, 'Navy Blue', 'XXL', 'LW-448-XXL', 25),
(449, 'Sky Blue', 'S', 'LW-449-S', 46),
(449, 'Sky Blue', 'M', 'LW-449-M', 36),
(449, 'Sky Blue', 'L', 'LW-449-L', 26),
(449, 'Sky Blue', 'XL', 'LW-449-XL', 26),
(449, 'Sky Blue', 'XXL', 'LW-449-XXL', 26),
(450, 'Cream', 'S', 'LW-450-S', 23),
(450, 'Cream', 'M', 'LW-450-M', 28),
(450, 'Cream', 'L', 'LW-450-L', 26),
(450, 'Cream', 'XL', 'LW-450-XL', 29),
(450, 'Cream', 'XXL', 'LW-450-XXL', 28),
(451, 'Olive Green', 'S', 'LW-451-S', 23),
(451, 'Olive Green', 'M', 'LW-451-M', 46),
(451, 'Olive Green', 'L', 'LW-451-L', 49),
(451, 'Olive Green', 'XL', 'LW-451-XL', 29),
(451, 'Olive Green', 'XXL', 'LW-451-XXL', 49);
